version: '3.8'

services:
  quickr:
    build: .
    environment:
      - APP_BASE_URL
      - JWT_SECRET
      - ADMIN_EMAIL
      - ADMIN_NAME
      - SENDINBLUE_API_KEY
      - SENDER_EMAIL
      - SENDER_NAME
      - BREVO_API_BASE
    volumes:
      - quickr_data:/app/data
    restart: unless-stopped
    networks:
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.quickr.rule=Host(`quickr.codeas.me`)"
      - "traefik.http.routers.quickr.entrypoints=websecure"
      - "traefik.http.routers.quickr.tls.certresolver=letsencrypt"

volumes:
  quickr_data:
    driver: local

networks:
  traefik_default:
    external: true